# Uncomment the next line to define a global platform for your project
# platform :ios, '7.0'

target 'BaiduMapDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaiduMapDemo

    pod 'BaiduMapKit' #百度地图SDK

end
